version: '3.8'

services:
  db_main:
    image: postgres
    env_file:
      - ./environment/.env.dev
    ports:
      - "5434:5434"
    volumes:
      - db_main:/var/lib/postgresql/data
  redis_main:
    image: redis:alpine
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD --port $$REDIS_PORT"
    env_file:
      - ./environment/.env.dev
    ports:
      - "6379:6379"

  db_test:
    image: postgres
    env_file:
      - ./environment/.env.test
    ports:
      - "5435:5435"
  redis_test:
    image: redis:alpine
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD --port $$REDIS_PORT"
    env_file:
      - ./environment/.env.test
    ports:
      - "6380:6380"
volumes:
  db_main: