"""initial migration

Revision ID: 733c13bc20b5
Revises: 
Create Date: 2024-01-06 20:34:14.560629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733c13bc20b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('auth_level', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('auth_level in (0, 1, 2)', name='auth_level_in_range'),
    sa.CheckConstraint('length(username) > 5', name='name_at_least_5_chars'),
    sa.CheckConstraint('status in (0, 1, 2)', name='status_in_range'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
